# Generated by Django 6.0.3 on 2026-03-24 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='MusicBrainz ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='MusicBrainz ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('picture', models.CharField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='MusicBrainz ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('precision', models.SmallIntegerField(choices=[(0, 'None'), (1, 'Year'), (2, 'Month'), (3, 'Day')], default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setsearch.artist')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setsearch.venue')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('date'), nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbid', models.CharField(blank=True, max_length=36, unique=True, verbose_name='MusicBrainz ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('picture', models.URLField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setsearch.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setsearch.concert')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'indexes': [models.Index(fields=['concert', 'timestamp'], name='setsearch_c_concert_0e1625_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setsearch.concert')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendances',
                'indexes': [models.Index(fields=['user', 'concert'], name='setsearch_a_user_id_184138_idx')],
            },
        ),
        migrations.CreateModel(
            name='SetlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setsearch.concert')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setsearch.song')),
            ],
            options={
                'verbose_name': 'setlist entry',
                'verbose_name_plural': 'setlist entries',
                'indexes': [models.Index(fields=['concert', 'position'], name='setsearch_s_concert_c2cddc_idx')],
            },
        ),
    ]
