# Generated by Django 6.0.3 on 2026-03-25 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setsearch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='MusicBrainz ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='MusicBrainz ID'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='mbid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='MusicBrainz ID'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(condition=models.Q(('mbid__isnull', False)), fields=('mbid',), name='artist_unique_non_null_mbid'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('user', 'concert'), name='unique_user_concert'),
        ),
        migrations.AddConstraint(
            model_name='setlistentry',
            constraint=models.UniqueConstraint(fields=('concert', 'position'), name='unique_concert_position'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(condition=models.Q(('mbid__isnull', False)), fields=('mbid',), name='song_unique_non_null_mbid'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(condition=models.Q(('mbid__isnull', False)), fields=('mbid',), name='venue_unique_non_null_mbid'),
        ),
    ]
