# Generated by Django 6.0.3 on 2026-03-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=255),
            preserve_default=False,
        ),
    ]
