# Generated by Django 6.0.3 on 2026-03-13 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setsearch', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='date',
        ),
        migrations.AddField(
            model_name='concert',
            name='day',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='month',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='year',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concert',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
